ARG BASE_IMAGE=debian:buster-slim

FROM ${BASE_IMAGE}

LABEL maintainer="Pavlo Ratushnyi<pavel.dhq@gmail.com>" 

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

RUN apt-get update && apt-get install -y \
        apt-transport-https \
        lsb-release \
        ca-certificates \
        locales \
        locales-all \
        software-properties-common \
        gpg \
        wget

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
RUN apt-get update
